import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import * as bcrypt from 'bcryptjs';

const connectionString = process.env.DATABASE_URL || 'postgresql://co2user:co2pass@localhost:5432/co2rechner';
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Seeding database...');

  // Seed Super Admin
  const adminEmail = process.env.ADMIN_EMAIL || 'admin@co2rechner.de';
  const adminPassword = process.env.ADMIN_PASSWORD || 'changeme123';
  const hashedPassword = await bcrypt.hash(adminPassword, 12);

  await prisma.superAdmin.upsert({
    where: { email: adminEmail },
    update: {
      passwordHash: hashedPassword,
    },
    create: {
      email: adminEmail,
      passwordHash: hashedPassword,
    },
  });
  console.log(`✅ Super Admin created: ${adminEmail}`);

  // Seed Quiz Questions
  const questions = [
    // ===== MOBILITÄT (Mobility) - 15 Questions =====
    {
      category: 'mobility',
      questionText: 'Wie weit ist dein Schulweg (einfache Strecke)?',
      questionType: 'slider',
      unit: 'km',
      co2Factor: 0.0,
      minValue: 0,
      maxValue: 50,
      step: 0.5,
      defaultValue: 5,
      helpText: 'Schätze die Entfernung von deinem Zuhause zur Schule.',
      orderIndex: 1,
    },
    {
      category: 'mobility',
      questionText: 'Wie kommst du normalerweise zur Schule?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Zu Fuß', value: 0 },
        { label: 'Fahrrad', value: 0 },
        { label: 'Bus / Straßenbahn', value: 0.089 },
        { label: 'Zug / S-Bahn', value: 0.055 },
        { label: 'Auto (alleine im Auto)', value: 0.152 },
        { label: 'Fahrgemeinschaft (2+ Personen)', value: 0.076 },
        { label: 'E-Bike / E-Scooter', value: 0.005 },
      ]),
      unit: 'kg CO₂/km',
      co2Factor: 1.0,
      helpText: 'Der CO₂-Faktor hängt vom Verkehrsmittel ab.',
      orderIndex: 2,
    },
    {
      category: 'mobility',
      questionText: 'An wie vielen Tagen pro Woche fährst du zur Schule?',
      questionType: 'slider',
      unit: 'Tage',
      co2Factor: 0.0,
      minValue: 1,
      maxValue: 6,
      step: 1,
      defaultValue: 5,
      helpText: 'Normalerweise 5 Tage, aber manchmal weniger.',
      orderIndex: 3,
    },
    {
      category: 'mobility',
      questionText: 'Wie viele Kilometer fährt deine Familie pro Woche mit dem Auto?',
      questionType: 'slider',
      unit: 'km',
      co2Factor: 0.152,
      minValue: 0,
      maxValue: 500,
      step: 10,
      defaultValue: 100,
      helpText: 'Schätze die gesamten Auto-Kilometer deiner Familie pro Woche.',
      orderIndex: 4,
    },
    {
      category: 'mobility',
      questionText: 'Wie viele Personen leben in deinem Haushalt?',
      questionType: 'slider',
      unit: 'Personen',
      co2Factor: 0.0,
      minValue: 1,
      maxValue: 8,
      step: 1,
      defaultValue: 3,
      helpText: 'Wird verwendet um die Autokilometer pro Person zu berechnen.',
      orderIndex: 5,
    },
    {
      category: 'mobility',
      questionText: 'Hat deine Familie ein Auto?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Nein', value: 0 },
        { label: 'Ja, einen Benziner', value: 1 },
        { label: 'Ja, einen Diesel', value: 1.1 },
        { label: 'Ja, ein Hybrid', value: 0.6 },
        { label: 'Ja, ein Elektroauto', value: 0.05 },
        { label: 'Ja, mehrere Autos', value: 1.5 },
      ]),
      unit: 'Faktor',
      co2Factor: 1.0,
      helpText: 'Der Autotyp beeinflusst die CO₂-Emissionen erheblich.',
      orderIndex: 6,
    },
    {
      category: 'mobility',
      questionText: 'Wie oft bist du im letzten Jahr geflogen (Hin- und Rückflug)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Gar nicht', value: 0 },
        { label: '1 Kurzstrecke (z.B. innerhalb Europas)', value: 500 },
        { label: '2 Kurzstrecken', value: 1000 },
        { label: '1 Langstrecke (z.B. USA, Asien)', value: 2500 },
        { label: '1 Kurzstrecke + 1 Langstrecke', value: 3000 },
        { label: 'Mehr als 2 Flüge', value: 4000 },
      ]),
      unit: 'kg CO₂',
      co2Factor: 1.0,
      helpText: 'Flugreisen haben einen sehr hohen CO₂-Ausstoß!',
      orderIndex: 7,
    },
    {
      category: 'mobility',
      questionText: 'Wie oft nutzt du öffentliche Verkehrsmittel (außer Schulweg)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Täglich', value: 300 },
        { label: 'Mehrmals pro Woche', value: 200 },
        { label: 'Einmal pro Woche', value: 100 },
        { label: 'Selten (ein paar Mal im Monat)', value: 40 },
        { label: 'Nie', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Bus, Bahn, Straßenbahn in deiner Freizeit.',
      orderIndex: 8,
    },
    {
      category: 'mobility',
      questionText: 'Fährst du in den Urlaub meistens mit dem Auto oder Flugzeug?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Wir fahren selten in den Urlaub', value: 0 },
        { label: 'Meistens mit dem Auto (nah)', value: 150 },
        { label: 'Meistens mit dem Auto (weit)', value: 400 },
        { label: 'Meistens mit dem Zug', value: 80 },
        { label: 'Meistens mit dem Flugzeug', value: 1500 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Wie reist deine Familie normalerweise in den Urlaub?',
      orderIndex: 9,
    },
    {
      category: 'mobility',
      questionText: 'Wie oft wirst du mit dem Auto zu Hobbys/Freunden gefahren?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nie (gehe zu Fuß/Rad)', value: 0 },
        { label: '1-2 Mal pro Woche', value: 80 },
        { label: '3-4 Mal pro Woche', value: 160 },
        { label: 'Fast täglich', value: 300 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Elterntaxi zu Sport, Musik, Freunden etc.',
      orderIndex: 10,
    },
    {
      category: 'mobility',
      questionText: 'Besitzt du ein Mofa, Motorrad oder Motorroller?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Nein', value: 0 },
        { label: 'Ja, fahre selten', value: 100 },
        { label: 'Ja, fahre regelmäßig', value: 350 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 11,
    },
    {
      category: 'mobility',
      questionText: 'Nutzt du Carsharing oder Mitfahrgelegenheiten?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, regelmäßig', value: -50 },
        { label: 'Manchmal', value: -20 },
        { label: 'Nein', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr (Einsparung)',
      co2Factor: 1.0,
      helpText: 'Geteilte Mobilität kann CO₂ sparen.',
      orderIndex: 12,
    },
    {
      category: 'mobility',
      questionText: 'Gehst du regelmäßig zu Fuß oder fährst Fahrrad in der Freizeit?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Ja, fast immer', value: -30 },
        { label: 'Oft', value: -15 },
        { label: 'Manchmal', value: 0 },
        { label: 'Selten', value: 20 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 13,
    },
    {
      category: 'mobility',
      questionText: 'Wie lange dauert dein durchschnittlicher Schulweg (eine Richtung)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Unter 10 Minuten', value: 0 },
        { label: '10-20 Minuten', value: 0 },
        { label: '20-40 Minuten', value: 0 },
        { label: 'Über 40 Minuten', value: 0 },
      ]),
      unit: 'Minuten',
      co2Factor: 0,
      helpText: 'Dies hilft bei der Einordnung deines Schulwegs.',
      orderIndex: 14,
    },
    {
      category: 'mobility',
      questionText: 'Hast du ein Deutschlandticket oder eine ÖPNV-Monatskarte?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja', value: -50 },
        { label: 'Nein', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'ÖPNV-Nutzung reduziert den CO₂-Fußabdruck.',
      orderIndex: 15,
    },

    // ===== ERNÄHRUNG (Food) - 15 Questions =====
    {
      category: 'food',
      questionText: 'Wie würdest du deine Ernährung beschreiben?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Vegan', value: 1000 },
        { label: 'Vegetarisch', value: 1200 },
        { label: 'Flexitarisch (wenig Fleisch)', value: 1500 },
        { label: 'Mischkost (normal)', value: 1800 },
        { label: 'Viel Fleisch', value: 2200 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Fleischkonsum hat den größten Einfluss auf den CO₂-Fußabdruck bei der Ernährung.',
      orderIndex: 16,
    },
    {
      category: 'food',
      questionText: 'Wie oft isst du Rindfleisch pro Woche?',
      questionType: 'slider',
      unit: 'Mal',
      co2Factor: 150,
      minValue: 0,
      maxValue: 7,
      step: 1,
      defaultValue: 1,
      helpText: 'Rindfleisch verursacht besonders hohe Emissionen (~13 kg CO₂ pro kg).',
      orderIndex: 17,
    },
    {
      category: 'food',
      questionText: 'Wie oft isst du Schweine- oder Hühnerfleisch pro Woche?',
      questionType: 'slider',
      unit: 'Mal',
      co2Factor: 50,
      minValue: 0,
      maxValue: 14,
      step: 1,
      defaultValue: 3,
      helpText: 'Schwein und Huhn verursachen weniger CO₂ als Rind.',
      orderIndex: 18,
    },
    {
      category: 'food',
      questionText: 'Wie oft isst du Milchprodukte (Käse, Joghurt, Milch)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nie (pflanzliche Alternativen)', value: 0 },
        { label: 'Selten', value: 100 },
        { label: 'Regelmäßig', value: 250 },
        { label: 'Täglich, viel', value: 400 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Milchproduktion verursacht Methan-Emissionen.',
      orderIndex: 19,
    },
    {
      category: 'food',
      questionText: 'Kaufst du regionale und saisonale Lebensmittel?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Ja, meistens', value: -100 },
        { label: 'Manchmal', value: -30 },
        { label: 'Selten', value: 0 },
        { label: 'Achte nicht darauf', value: 50 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Regionale Produkte haben kürzere Transportwege.',
      orderIndex: 20,
    },
    {
      category: 'food',
      questionText: 'Kaufst du Bio-Lebensmittel?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, meistens', value: -80 },
        { label: 'Teilweise', value: -30 },
        { label: 'Selten / Nie', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Bio-Landwirtschaft verbraucht oft weniger fossile Energie.',
      orderIndex: 21,
    },
    {
      category: 'food',
      questionText: 'Wie oft wirfst du Lebensmittel weg?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Fast nie', value: 0 },
        { label: 'Selten', value: 50 },
        { label: 'Manchmal', value: 120 },
        { label: 'Regelmäßig', value: 200 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'In Deutschland werden ca. 75 kg Lebensmittel pro Person und Jahr weggeworfen.',
      orderIndex: 22,
    },
    {
      category: 'food',
      questionText: 'Wie oft isst du in der Schulmensa oder Kantine?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Täglich', value: 100 },
        { label: '2-3 Mal pro Woche', value: 50 },
        { label: 'Selten', value: 20 },
        { label: 'Nie (bringe eigenes Essen mit)', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 23,
    },
    {
      category: 'food',
      questionText: 'Trinkst du Leitungswasser oder kaufst du Wasser in Flaschen?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Meistens Leitungswasser', value: 0 },
        { label: 'Beides', value: 15 },
        { label: 'Meistens Flaschenwasser', value: 35 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Plastikflaschen verursachen zusätzliche Emissionen.',
      orderIndex: 24,
    },
    {
      category: 'food',
      questionText: 'Isst du viel Tiefkühlkost oder Fertiggerichte?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nie / selten', value: 0 },
        { label: 'Manchmal', value: 30 },
        { label: 'Regelmäßig', value: 70 },
        { label: 'Sehr oft', value: 120 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Tiefkühlkost benötigt viel Energie für die Kühlung.',
      orderIndex: 25,
    },
    {
      category: 'food',
      questionText: 'Wie oft isst du Fisch oder Meeresfrüchte?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nie', value: 0 },
        { label: '1 Mal pro Woche', value: 40 },
        { label: '2-3 Mal pro Woche', value: 100 },
        { label: 'Häufiger', value: 160 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 26,
    },
    {
      category: 'food',
      questionText: 'Isst du exotische Früchte (Avocado, Mango, etc.)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nie', value: 0 },
        { label: 'Selten', value: 20 },
        { label: 'Regelmäßig', value: 60 },
        { label: 'Häufig', value: 100 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Exotische Früchte haben lange Transportwege.',
      orderIndex: 27,
    },
    {
      category: 'food',
      questionText: 'Wie oft kocht deine Familie selbst (statt Essen zu bestellen)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Fast immer selbst', value: -30 },
        { label: 'Meistens selbst', value: 0 },
        { label: 'Oft bestellt / auswärts', value: 60 },
        { label: 'Sehr oft bestellt', value: 120 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 28,
    },
    {
      category: 'food',
      questionText: 'Achtest du auf die Verpackung beim Einkaufen?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, kaufe möglichst unverpackt', value: -40 },
        { label: 'Manchmal', value: 0 },
        { label: 'Nein, achte nicht darauf', value: 30 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 29,
    },
    {
      category: 'food',
      questionText: 'Nutzt du pflanzliche Milchalternativen (Hafermilch, Sojamilch)?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, ausschließlich', value: -60 },
        { label: 'Manchmal', value: -20 },
        { label: 'Nein', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Pflanzliche Milch hat einen deutlich geringeren CO₂-Fußabdruck.',
      orderIndex: 30,
    },

    // ===== ENERGIE (Energy) - 15 Questions =====
    {
      category: 'energy',
      questionText: 'Wie wird euer Zuhause hauptsächlich beheizt?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Erdgas', value: 1500 },
        { label: 'Heizöl', value: 2000 },
        { label: 'Fernwärme', value: 1000 },
        { label: 'Wärmepumpe', value: 400 },
        { label: 'Holz / Pellets', value: 300 },
        { label: 'Elektroheizung', value: 1800 },
        { label: 'Weiß ich nicht', value: 1200 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Die Heizung macht oft den größten Teil des Energie-Fußabdrucks aus.',
      orderIndex: 31,
    },
    {
      category: 'energy',
      questionText: 'Wie groß ist eure Wohnung/euer Haus ungefähr?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Kleine Wohnung (unter 60 m²)', value: 0.6 },
        { label: 'Mittlere Wohnung (60-100 m²)', value: 0.85 },
        { label: 'Große Wohnung (100-150 m²)', value: 1.1 },
        { label: 'Haus (über 150 m²)', value: 1.4 },
        { label: 'Großes Haus (über 200 m²)', value: 1.8 },
      ]),
      unit: 'Faktor',
      co2Factor: 1.0,
      helpText: 'Größere Wohnfläche = mehr Energie zum Heizen.',
      orderIndex: 32,
    },
    {
      category: 'energy',
      questionText: 'Bezieht ihr Ökostrom?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, 100% Ökostrom', value: -400 },
        { label: 'Teilweise', value: -150 },
        { label: 'Nein / Weiß nicht', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Ökostrom aus Wind und Solar verursacht kaum direkte Emissionen.',
      orderIndex: 33,
    },
    {
      category: 'energy',
      questionText: 'Habt ihr eine Solaranlage auf dem Dach?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja', value: -300 },
        { label: 'Nein', value: 0 },
        { label: 'Weiß ich nicht', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 34,
    },
    {
      category: 'energy',
      questionText: 'Wie warm ist es bei euch im Winter in der Wohnung?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Unter 19°C (kühl)', value: -200 },
        { label: '19-20°C', value: -100 },
        { label: '21°C (Normaltemperatur)', value: 0 },
        { label: '22-23°C', value: 150 },
        { label: 'Über 23°C (sehr warm)', value: 300 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Jedes Grad weniger spart ca. 6% Heizenergie!',
      orderIndex: 35,
    },
    {
      category: 'energy',
      questionText: 'Wie lange duschst du durchschnittlich?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Unter 5 Minuten', value: 80 },
        { label: '5-10 Minuten', value: 200 },
        { label: '10-15 Minuten', value: 350 },
        { label: 'Über 15 Minuten', value: 500 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Warmwasser braucht viel Energie!',
      orderIndex: 36,
    },
    {
      category: 'energy',
      questionText: 'Wie oft duschst du pro Woche?',
      questionType: 'slider',
      unit: 'Mal',
      co2Factor: 15,
      minValue: 1,
      maxValue: 14,
      step: 1,
      defaultValue: 5,
      orderIndex: 37,
    },
    {
      category: 'energy',
      questionText: 'Schaltest du elektrische Geräte aus oder lässt du sie im Standby?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Immer ganz ausschalten', value: -30 },
        { label: 'Meistens ausschalten', value: 0 },
        { label: 'Oft im Standby', value: 50 },
        { label: 'Fast immer im Standby', value: 100 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Standby verbraucht unnötig Strom!',
      orderIndex: 38,
    },
    {
      category: 'energy',
      questionText: 'Nutzt ihr LED-Lampen?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, überall', value: -40 },
        { label: 'Teilweise', value: 0 },
        { label: 'Nein / alte Glühbirnen', value: 60 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 39,
    },
    {
      category: 'energy',
      questionText: 'Wie oft nutzt du den Wäschetrockner?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nie (Wäscheleine)', value: 0 },
        { label: 'Selten', value: 30 },
        { label: 'Regelmäßig', value: 80 },
        { label: 'Fast immer', value: 150 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Wäschetrockner sind große Stromverbraucher.',
      orderIndex: 40,
    },
    {
      category: 'energy',
      questionText: 'Wie alt ist euer Haus/eure Wohnung?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Neubau (nach 2010, gut gedämmt)', value: -200 },
        { label: 'Renoviert / saniert', value: -100 },
        { label: 'Mittelalt (1970-2010)', value: 0 },
        { label: 'Altbau (vor 1970)', value: 200 },
        { label: 'Weiß ich nicht', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Gut gedämmte Häuser verbrauchen deutlich weniger Heizenergie.',
      orderIndex: 41,
    },
    {
      category: 'energy',
      questionText: 'Habt ihr eine Klimaanlage?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Nein', value: 0 },
        { label: 'Ja, nutzen wir selten', value: 50 },
        { label: 'Ja, nutzen wir oft', value: 200 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 42,
    },
    {
      category: 'energy',
      questionText: 'Wie oft wäschst du deine Wäsche pro Woche?',
      questionType: 'slider',
      unit: 'Waschgänge',
      co2Factor: 10,
      minValue: 0,
      maxValue: 10,
      step: 1,
      defaultValue: 3,
      helpText: 'Pro Waschgang ca. 0,5-1 kWh Strom.',
      orderIndex: 43,
    },
    {
      category: 'energy',
      questionText: 'Bei welcher Temperatur wäschst du meistens?',
      questionType: 'select',
      options: JSON.stringify([
        { label: '30°C (kalt)', value: -20 },
        { label: '40°C', value: 0 },
        { label: '60°C', value: 30 },
        { label: '90°C (heiß)', value: 60 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: '30°C statt 60°C spart ca. 50% Energie.',
      orderIndex: 44,
    },
    {
      category: 'energy',
      questionText: 'Lüftest du im Winter mit gekipptem Fenster oder Stoßlüften?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Stoßlüften (kurz, ganz öffnen)', value: -50 },
        { label: 'Beides', value: 0 },
        { label: 'Meistens Kipplüften', value: 80 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Kipplüften verschwendet viel Heizenergie!',
      orderIndex: 45,
    },

    // ===== KONSUM (Consumption) - 15 Questions =====
    {
      category: 'consumption',
      questionText: 'Wie oft kaufst du neue Kleidung?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Selten (ein paar Mal im Jahr)', value: 100 },
        { label: 'Alle paar Monate', value: 200 },
        { label: 'Monatlich', value: 400 },
        { label: 'Mehrmals im Monat (Fast Fashion)', value: 700 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Die Textilindustrie ist für ca. 10% der weltweiten CO₂-Emissionen verantwortlich.',
      orderIndex: 46,
    },
    {
      category: 'consumption',
      questionText: 'Kaufst du Second-Hand Kleidung?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Ja, oft', value: -100 },
        { label: 'Manchmal', value: -30 },
        { label: 'Nie', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 47,
    },
    {
      category: 'consumption',
      questionText: 'Wie viele Stunden pro Tag nutzt du digitale Geräte (Smartphone, Tablet, PC)?',
      questionType: 'slider',
      unit: 'Stunden',
      co2Factor: 20,
      minValue: 0,
      maxValue: 16,
      step: 0.5,
      defaultValue: 4,
      helpText: 'Streaming, Gaming, Social Media verbrauchen Strom in Rechenzentren.',
      orderIndex: 48,
    },
    {
      category: 'consumption',
      questionText: 'Wie viele Stunden pro Tag streamst du Videos (Netflix, YouTube, TikTok)?',
      questionType: 'slider',
      unit: 'Stunden',
      co2Factor: 25,
      minValue: 0,
      maxValue: 10,
      step: 0.5,
      defaultValue: 2,
      helpText: 'Video-Streaming verursacht ca. 55g CO₂ pro Stunde.',
      orderIndex: 49,
    },
    {
      category: 'consumption',
      questionText: 'Wie oft bestellst du online?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Selten (ein paar Mal im Jahr)', value: 20 },
        { label: 'Monatlich', value: 60 },
        { label: 'Wöchentlich', value: 150 },
        { label: 'Mehrmals pro Woche', value: 300 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Online-Bestellungen verursachen Verpackungsmüll und Lieferwege.',
      orderIndex: 50,
    },
    {
      category: 'consumption',
      questionText: 'Wie oft kaufst du neue Elektronikgeräte (Handy, Kopfhörer, etc.)?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Alle 3-4 Jahre', value: 50 },
        { label: 'Alle 2 Jahre', value: 100 },
        { label: 'Jedes Jahr', value: 200 },
        { label: 'Mehrmals im Jahr', value: 350 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Die Produktion eines Smartphones verursacht ca. 70 kg CO₂.',
      orderIndex: 51,
    },
    {
      category: 'consumption',
      questionText: 'Reparierst du kaputte Sachen oder kaufst du neu?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Repariere meistens', value: -50 },
        { label: 'Manchmal reparieren', value: -20 },
        { label: 'Kaufe meistens neu', value: 50 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 52,
    },
    {
      category: 'consumption',
      questionText: 'Wie gehst du mit Müll um?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Trenne alles sorgfältig', value: -40 },
        { label: 'Trenne meistens', value: -15 },
        { label: 'Trenne manchmal', value: 0 },
        { label: 'Trenne selten / gar nicht', value: 40 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Recycling spart Rohstoffe und Energie.',
      orderIndex: 53,
    },
    {
      category: 'consumption',
      questionText: 'Nutzt du eine Trinkflasche oder kaufst du Einwegflaschen?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Wiederverwendbare Flasche', value: -10 },
        { label: 'Beides', value: 10 },
        { label: 'Meistens Einwegflaschen', value: 30 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 54,
    },
    {
      category: 'consumption',
      questionText: 'Wie viele Hobbys mit hohem Ressourcenverbrauch hast du?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Keine / wenig (Lesen, Sport, Musik)', value: 0 },
        { label: 'Eins (z.B. Gaming, Motorsport)', value: 100 },
        { label: 'Mehrere ressourcenintensive Hobbys', value: 250 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Manche Hobbys verbrauchen mehr Energie als andere.',
      orderIndex: 55,
    },
    {
      category: 'consumption',
      questionText: 'Wie oft kaufst du neue Möbel oder Einrichtung?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Sehr selten', value: 20 },
        { label: 'Ab und zu', value: 60 },
        { label: 'Regelmäßig', value: 150 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 56,
    },
    {
      category: 'consumption',
      questionText: 'Nutzt du Papier oder digital für Schulaufgaben?',
      questionType: 'radio',
      options: JSON.stringify([
        { label: 'Hauptsächlich digital', value: 10 },
        { label: 'Beides', value: 20 },
        { label: 'Hauptsächlich Papier', value: 40 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 57,
    },
    {
      category: 'consumption',
      questionText: 'Wie gehst du mit Geschenken um?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Selbstgemacht / Erlebnisse', value: -20 },
        { label: 'Gebrauchte / nachhaltige Geschenke', value: 0 },
        { label: 'Neue Produkte (normal)', value: 50 },
        { label: 'Viele und teure Geschenke', value: 100 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      orderIndex: 58,
    },
    {
      category: 'consumption',
      questionText: 'Hast du Haustiere?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Nein', value: 0 },
        { label: 'Kleintier (Hamster, Fisch, etc.)', value: 50 },
        { label: 'Katze', value: 200 },
        { label: 'Kleiner Hund', value: 500 },
        { label: 'Großer Hund', value: 800 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Haustiere haben auch einen CO₂-Fußabdruck, vor allem durch Futter.',
      orderIndex: 59,
    },
    {
      category: 'consumption',
      questionText: 'Wie engagierst du dich für die Umwelt?',
      questionType: 'select',
      options: JSON.stringify([
        { label: 'Sehr aktiv (Demos, Projekte, Verein)', value: -50 },
        { label: 'Achte im Alltag darauf', value: -20 },
        { label: 'Ein bisschen', value: 0 },
        { label: 'Kaum / gar nicht', value: 0 },
      ]),
      unit: 'kg CO₂/Jahr',
      co2Factor: 1.0,
      helpText: 'Dein Engagement inspiriert andere!',
      orderIndex: 60,
    },
  ];

  // Delete existing questions and re-seed
  await prisma.quizQuestion.deleteMany({});

  function getQuestionTier(orderIndex: number): number {
    const tier1 = [1, 2, 7, 16, 17, 31, 36, 46, 48, 53];
    const tier2 = [3, 4, 6, 8, 9, 18, 19, 20, 21, 22, 32, 33, 34, 35, 37, 47, 49, 50, 51, 59];
    if (tier1.includes(orderIndex)) return 1;
    if (tier2.includes(orderIndex)) return 2;
    return 3;
  }
  
  for (const q of questions) {
    await prisma.quizQuestion.create({
      data: {
        category: q.category,
        questionText: q.questionText,
        questionType: q.questionType,
        options: q.options ? JSON.parse(q.options as string) : null,
        unit: q.unit || null,
        co2Factor: q.co2Factor,
        minValue: q.minValue ?? null,
        maxValue: q.maxValue ?? null,
        step: q.step ?? null,
        defaultValue: q.defaultValue ?? null,
        helpText: q.helpText || null,
        orderIndex: q.orderIndex,
        tier: getQuestionTier(q.orderIndex),
      },
    });
  }

  console.log(`✅ Seeded ${questions.length} quiz questions`);
  console.log('🌱 Seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
